file_format: "1"
id: BB40
name: BB40
type: shield
url: https://mechwild.com/product/bb40/
requires: [blackpill]
features:
  - keys
  - encoder
include:
  - board: pillbug
    shield: BB40
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
